
services:
  - type: web
    name: gde-moi-dengi-service
    env: node
    plan: free
    # Сначала генерируем клиент Prisma, затем мигрируем БД и собираем приложение
    buildCommand: npm install && npm run prisma:generate && npm run build
    # Запуск сервера, который раздает и API, и Статику
    startCommand: npm run prisma:migrate && npm run start
    healthCheckPath: /health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: budget-db
          property: connectionString
      - key: BOT_TOKEN
        sync: false
      - key: ADMIN_JWT_SECRET
        generateValue: true
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000

databases:
  - name: budget-db
    plan: free
